# Generated by Django 4.2.5 on 2023-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_giantsdata_giants_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giantsdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='jetsdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='knicksdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='metsdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='netsdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='yankeesdata',
            name='date',
            field=models.CharField(max_length=5),
        ),
    ]
