# Generated by Django 4.2.5 on 2023-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_giantsdata_date_alter_jetsdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giantsdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jetsdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='knicksdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='metsdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='netsdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='yankeesdata',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
